apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
  containers:
    - name: podcontainer1
      image: nginx
      volumeMounts:
        - mountPath: "/data"
          name: pv-storage